%\VignetteIndexEntry{HD2013SGI}
%\VignettePackage{HD2013SGI}
\documentclass[10pt,a4paper,oneside]{article}

<<style, echo=FALSE, results=tex>>=
  BiocStyle::latex()
@

\bioctitle[Mapping genetic interactions in human cancer
cells, Laufer, Fischer et al., 2013]{\textsf{\textbf{Mapping
      genetic interactions in human cancer cells with RNAi
      and multiparametric phenotyping}\\
    Christina Laufer, Bernd Fischer, Maximilian Billmann,
    Wolfgang Huber, and Michael Boutros. Nature Methods
    (2013) 10(5):427-31 doi: 10.1038/nmeth.2436}}
\author{Bernd Fischer\\[1em]European Molecular Biology Laboratory (EMBL),\\ Heidelberg, Germany\\ \texttt{bernd.fischer@embl.de}}

\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle
\tableofcontents


\section{Introduction}
This document is associated with the \Bioconductor{} package \Rpackage{HD2013SGI},
which contains the data and the \R{} code for the statistical analysis
presented in the paper \\\\
\begin{center}
\begin{minipage}[t]{0.96\textwidth}
\textit{Mapping genetic interactions in human cancer cells with RNAi and multiparametric phenotyping}\\
Christina Laufer, Bernd Fischer, Maximilian Billmann, Wolfgang Huber, and Michael Boutros\\
Nature Methods (2013) 10(5):427-31\\ 
doi: 10.1038/nmeth.2436.\\
\\
\end{minipage}
\end{center}

In Section~\ref{dataAccess}, the access to the data is
described. Section~\ref{Figures} shows the figures from the original
publication and links each figure to one of the subsequent sections,
which describe the statistical analyses in the order in which they
were executed. The \R{} code within each section can be executed
independently of the other sections.  Intermediate results from each
section are available in the form of \R{} data objects.

To install the \Biocexptpkg{HD2013SGI}, please start a current version of
\R{} and type
<<installation,eval=FALSE>>=
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("HD2013SGI")
@

\input{sec02_dataAccess.tex}
\input{sec03_figures.tex}
\input{sec04_imageProcessing.tex}
\input{sec05_convertData.tex}
\input{sec06_rawDataProcessing.tex}
\input{sec07_exampleInteractions.tex}
\input{sec08_siRNAcorrelation.tex}
\input{sec09_heatmaps.tex}
\input{sec10_smallCellNumber.tex}
\input{sec11_distributionOfInteractions.tex}
\input{sec12_scatterplots.tex}
\input{sec13_screenplots.tex}
\input{sec14_table.tex}

<<moreSourceFiles, echo=FALSE,eval=FALSE>>=
# the source files for single sections are in the folder:
system.file(file.path("doc","src"),package="HD2013SGI")
# the R scripts for single sections are in the folder:
system.file(file.path("doc"),package="HD2013SGI")
@ 

\section{Session info}
Here is the output of \Rfunction{sessionInfo} on the system on which this document was compiled:
<<installation2,echo=FALSE,results=hide>>=
library("HD2013SGI")
@
<<sessioninfo, results=tex, print=TRUE>>=
toLatex(sessionInfo())
@

<<bibstyle, results=tex, echo=FALSE>>=
if ((R.version$major <= 3) & (R.version$minor < 1.0)) {
  cat("\\bibliographystyle{unsrt}\n")
}
@

\bibliography{literature}

\end{document}
