
\section{Example phenotypes and interactions}\label{examplePhenotypes}
\subsection{Preliminaries}

<<exampleSingleKnockDownEffects1>>=
library("HD2013SGI")

data("Interactions",package="HD2013SGI")
data("mainEffects",package="HD2013SGI")

dir.create(file.path("result","Figures"),
           recursive=TRUE,showWarnings=FALSE)
@

\subsection{Examples of single knock down phenotypes}\label{exampleSingleKDPhenotypes}

Main effects are first summarized over all four siRNA design pairs and
divided by the median deviation to compute a z-score. Bars show the
mean of main effects calculated over the two replicates of the
screen. Circle symbols represent individual replicate
measurements. Main effects for five different phenotypes are plotted
for the two genes SETD8 and TCF20.

<<exampleSingleKnockDownEffects2,results=hide>>=
features = c("count", "nuc.0.s.area","nuc.0.m.eccentricity",
             "cell.Bact.m.eccentricity","cell.act.m.majoraxis")
ylim = c(-2.947124,7.329518)
@
<<exampleSingleKnockDownEffects3,echo=FALSE,results=hide>>=
pdf(file=file.path("result","Figures","singleKnockDown-SETD8.pdf"),
    width=2.5,height=5)
<<exampleSingleKnockDownEffects4,results=hide>>=
HD2013SGI:::plotExampleSingleGeneEffects(gene="SETD8",features,mainEffects,ylim)
<<exampleSingleKnockDownEffects5,echo=FALSE,results=hide>>=
dev.off()
pdf(file=file.path("result","Figures","singleKnockDown-TCF20.pdf"),
    width=2.5,height=5)
<<exampleSingleKnockDownEffects6,results=hide>>=
HD2013SGI:::plotExampleSingleGeneEffects(gene="TCF20",features,mainEffects,ylim)
<<exampleSingleKnockDownEffects7,echo=FALSE,results=hide>>=
dev.off()
@
\begin{center}
\includegraphics[width=0.3\textwidth]{result/Figures/singleKnockDown-SETD8.pdf}
\includegraphics[width=0.3\textwidth]{result/Figures/singleKnockDown-TCF20.pdf}
\end{center}

\subsection{Example of genetic interactions}\label{exampleDoubleKDPhenotypes}

Barcharts for example interactions are plotted.
<<exampleInteractions1,echo=FALSE,results=hide>>=
pdf(file=file.path("result","Figures","interaction-PHF16-SETD8.pdf"),
    height=4,width=3)
@
<<exampleInteractions1,results=hide>>=
HD2013SGI:::plotExampleInteractions(feature="cell.act.m.majoraxis",
                                    target="PHF16",query="SETD8",
                                    Interactions, mainEffects)
@
<<exampleInteractions2,echo=FALSE,results=hide>>=
dev.off()
pdf(file=file.path("result","Figures","interaction-SIN3A-RUVBL1.pdf"),
    height=4,width=3)
@
<<exampleInteractions3,results=hide>>=
HD2013SGI:::plotExampleInteractions(feature="nuc.0.m.eccentricity",
                                    target="SIN3A",query="RUVBL1",
                                    Interactions, mainEffects)
@
<<exampleInteractions4,echo=FALSE,results=hide>>=
dev.off()
@

\begin{center}
\includegraphics[width=0.3\textwidth]{result/Figures/interaction-PHF16-SETD8.pdf}
\includegraphics[width=0.3\textwidth]{result/Figures/interaction-SIN3A-RUVBL1.pdf}
\end{center}

\subsection{Overlap of interactions}\label{OverlapOfInteractions}

To show the overlap of interactions called in different phenotypes,
Interactions with an adjusted p-value of 0.01 are considered. 
<<overlapOfInteractions1>>=
features = c("nuc.0.s.area","nuc.0.m.majoraxis",
             "cell.Bact.m.eccentricity","cell.act.m.majoraxis")
SIG = Interactions$padj[,,,,features] <= 0.01
SIG[is.na(SIG)] = FALSE
@ 
The 5-dimensional array of boolean values indicating the significant
interactions is reshaped to a 2-dimensional table with one column for
each feature.
<<overlapOfInteractions2>>=
dim(SIG) = c(prod(dim(SIG)[1:4]),dim(SIG)[5])
row.names(SIG) = sprintf("A%d",seq_len(nrow(SIG)))
colnames(SIG) = HD2013SGI:::humanReadableNames[features]
@
A contingency table is computed considering all gene pairs that interact in
at leat one phenotype.
<<overlapOfInteractions3>>=
I = which(apply(SIG,1,any))
Overlap = table(as.data.frame(SIG[I,]))
print(Overlap)
save(Overlap, file=file.path("result","Figures","Overlap.rda"))
@

A Venn diagram can be generated with a webtool
(e.g. http://bioinfogp.cnb.csic.es/tools/venny/index.html). Lists of
identifiers of the significant genes are written be be used with the webtools.
<<overlapOfInteractions4,eval=FALSE>>=
L = apply(SIG,2,function(x) names(which(x)))
for (i in seq_along(L)) {
  writeLines(L[[i]],file.path("result","Figures",
                              sprintf("interactionlist%d.txt",i)))
}
@ 

In the original paper a Venn diagram is shown. An alternative plot
where the region areas are proportional to the numbers, is a mosaic
plot as shown here.
<<overlapOfInteractions5,echo=FALSE,results=hide>>=
pdf(file.path("result","Figures","Mosaicplot.pdf"))
@
<<overlapOfInteractions6,echo=FALSE,results=hide>>=
mosaic(Overlap, shade = TRUE)
@ 
<<overlapOfInteractions7,results=hide>>=
dev.off()
@
\begin{center}
  \includegraphics[width=0.7\textwidth]{result/Figures/Mosaicplot.pdf}
\end{center}

